// import { IOrder } from "@/types";

// export const ordersMock: IOrder[] = [
//     {
//         id: "1",
//         status: "pending",
//         order_type: "dine-in",
//         tableId: "123",
//         restaurantId: "resto-1",
//         userId: "user-1",
//         created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
//         items: [
//             { id: "a", name: "Pizza", description: "Napolitana", price: 10, quantity: 2 },
//             { id: "b", name: "Coca-Cola 350ml", description: "Bebida fría", price: 3, quantity: 1 },
//         ],
//         total_price: 23,
//     },
//     {
//         id: "2",
//         status: "in-process",
//         order_type: "dine-in",
//         tableId: "456",
//         restaurantId: "resto-1",
//         userId: "user-2",
//         created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
//         items: [
//             { id: "c", name: "Tarta de jamón y queso", description: "Casera", price: 8, quantity: 1 },
//             { id: "d", name: "Agua sin gas 500ml", description: "Agua mineral", price: 2, quantity: 1 },
//         ],
//         total_price: 10,
//     },
//     {
//         id: "3",
//         status: "completed",
//         order_type: "take-away",
//         tableId: "789",
//         restaurantId: "resto-1",
//         userId: "user-3",
//         created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
//         items: [{ id: "e", name: "Hamburguesa", description: "Con papas fritas", price: 12, quantity: 1 }],
//         total_price: 12,
//     },
//     {
//         id: "4",
//         status: "ready",
//         order_type: "dine-in",
//         tableId: "101",
//         restaurantId: "resto-2",
//         userId: "user-4",
//         created_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
//         items: [{ id: "f", name: "Ensalada César", description: "Con pollo", price: 9, quantity: 1 }],
//         total_price: 9,
//     },
//     {
//         id: "5",
//         status: "pending",
//         order_type: "take-away",
//         tableId: "102",
//         restaurantId: "resto-2",
//         userId: "user-5",
//         created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
//         items: [{ id: "g", name: "Wrap veggie", description: "Lechuga, tomate, hummus", price: 7, quantity: 1 }],
//         total_price: 7,
//     },
//     {
//         id: "6",
//         status: "ready",
//         order_type: "dine-in",
//         tableId: "103",
//         restaurantId: "resto-1",
//         userId: "user-6",
//         created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
//         items: [{ id: "h", name: "Milanesa con puré", description: "De ternera", price: 11, quantity: 1 }],
//         total_price: 11,
//     },
//     {
//         id: "7",
//         status: "completed",
//         order_type: "dine-in",
//         tableId: "104",
//         restaurantId: "resto-1",
//         userId: "user-7",
//         created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
//         items: [{ id: "i", name: "Empanadas", description: "Carne y queso", price: 4, quantity: 3 }],
//         total_price: 12,
//     },
//     {
//         id: "8",
//         status: "in-process",
//         order_type: "take-away",
//         tableId: "105",
//         restaurantId: "resto-2",
//         userId: "user-8",
//         created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
//         items: [{ id: "j", name: "Sándwich de pollo", description: "Con lechuga y tomate", price: 8, quantity: 1 }],
//         total_price: 8,
//     },
//     {
//         id: "9",
//         status: "pending",
//         order_type: "dine-in",
//         tableId: "106",
//         restaurantId: "resto-1",
//         userId: "user-9",
//         created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
//         items: [{ id: "k", name: "Tostadas", description: "Con mermelada", price: 5, quantity: 1 }],
//         total_price: 5,
//     },
//     {
//         id: "10",
//         status: "ready",
//         order_type: "take-away",
//         tableId: "107",
//         restaurantId: "resto-3",
//         userId: "user-10",
//         created_at: new Date(Date.now() - 16 * 60 * 1000).toISOString(),
//         items: [{ id: "l", name: "Smoothie", description: "Frutilla y banana", price: 6, quantity: 1 }],
//         total_price: 6,
//     },
//     {
//         id: "11",
//         status: "completed",
//         order_type: "dine-in",
//         tableId: "108",
//         restaurantId: "resto-1",
//         userId: "user-11",
//         created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
//         items: [{ id: "m", name: "Helado", description: "Chocolate", price: 4, quantity: 2 }],
//         total_price: 8,
//     },
//     {
//         id: "12",
//         status: "pending",
//         order_type: "take-away",
//         tableId: "109",
//         restaurantId: "resto-2",
//         userId: "user-12",
//         created_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
//         items: [{ id: "n", name: "Café", description: "Solo", price: 2, quantity: 1 }],
//         total_price: 2,
//     },
//     {
//         id: "13",
//         status: "ready",
//         order_type: "dine-in",
//         tableId: "110",
//         restaurantId: "resto-1",
//         userId: "user-13",
//         created_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
//         items: [{ id: "o", name: "Panqueques", description: "Con dulce de leche", price: 6, quantity: 1 }],
//         total_price: 6,
//     },
//     {
//         id: "14",
//         status: "in-process",
//         order_type: "dine-in",
//         tableId: "111",
//         restaurantId: "resto-2",
//         userId: "user-14",
//         created_at: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
//         items: [{ id: "p", name: "Ravioles", description: "De ricota", price: 9, quantity: 1 }],
//         total_price: 9,
//     },
//     {
//         id: "15",
//         status: "completed",
//         order_type: "take-away",
//         tableId: "112",
//         restaurantId: "resto-3",
//         userId: "user-15",
//         created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
//         items: [{ id: "q", name: "Lomito", description: "Con huevo y jamón", price: 13, quantity: 1 }],
//         total_price: 13,
//     },
//     {
//         id: "16",
//         status: "in-process",
//         order_type: "dine-in",
//         tableId: "113",
//         restaurantId: "resto-1",
//         userId: "user-16",
//         created_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
//         items: [{ id: "r", name: "Bife a caballo", description: "Con arroz", price: 14, quantity: 1 }],
//         total_price: 14,
//     },
//     {
//         id: "17",
//         status: "ready",
//         order_type: "take-away",
//         tableId: "114",
//         restaurantId: "resto-2",
//         userId: "user-17",
//         created_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
//         items: [{ id: "s", name: "Arepas", description: "Rellenas de queso", price: 7, quantity: 2 }],
//         total_price: 14,
//     },
//     {
//         id: "18",
//         status: "pending",
//         order_type: "dine-in",
//         tableId: "115",
//         restaurantId: "resto-3",
//         userId: "user-18",
//         created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
//         items: [{ id: "t", name: "Croissants", description: "Manteca", price: 3, quantity: 2 }],
//         total_price: 6,
//     },
// ];
